echo "Starting EN QA testing..."

echo "Q1:"
http POST localhost:8000/ask_question lang="en" question="How does COVID-19 spread?"
echo "Q2:"
http POST localhost:8000/ask_question lang="en" question="What are the symptoms of COVID-19?"
echo "Q3:"
http POST localhost:8000/ask_question lang="en" question="How do I know if it is COVID-19 or just the common cold?"
echo "Q4:"
http POST localhost:8000/ask_question lang="en" question="Can the virus that causes COVID-19 be transmitted through the air?"
echo "Q5:"
http POST localhost:8000/ask_question lang="en" question="What can I do to protect myself and prevent the spread of disease?"
echo "Q6:"
http POST localhost:8000/ask_question lang="en" question="Should I wear a mask while exercising?"
echo "Q7:"
http POST localhost:8000/ask_question lang="en" question="Are the symptoms of COVID-19 different in children than in adults?"
echo "Q8:"
http POST localhost:8000/ask_question lang="en" question="Are antibiotics effective in preventing or treating COVID-19?"
echo "Q9:"
http POST localhost:8000/ask_question lang="en" question="Can humans become infected with COVID-19 from an animal source?"
echo "Q10:"
http POST localhost:8000/ask_question lang="en" question="How long does the virus survive on surfaces?"

echo "Starting PT QA testing..."
echo "Q1:"
http POST localhost:8000/ask_question lang="pt" question="Como se transmite a COVID-19?"
echo "Q2:"
http POST localhost:8000/ask_question lang="pt" question="Quais são os sintomas da COVID-19?"
echo "Q3:"
http POST localhost:8000/ask_question lang="pt" question="Como posso saber se tenho COVID-19 ou uma constipação?"
echo "Q4:"
http POST localhost:8000/ask_question lang="pt" question="O vírus que transmite a COVID-19 pode ser transmitido pelo ar?"
echo "Q5:"
http POST localhost:8000/ask_question lang="pt" question="O que posso fazer para me proteger e evitar a disseminação da doença?"
echo "Q6:"
http POST localhost:8000/ask_question lang="pt" question="Devo usar máscara enquanto faço exercício?"
echo "Q7:"
http POST localhost:8000/ask_question lang="pt" question="Os sintomas da COVID-19 são diferentes nos adultos e nas crianças?"
echo "Q8:"
http POST localhost:8000/ask_question lang="pt" question="Os antibióticos são eficazes na prevenção ou tratamento da COVID-19?"
echo "Q9:"
http POST localhost:8000/ask_question lang="pt" question="Os humanos podem ser infetados com a COVID-19 através de animais?"
echo "Q10:"
http POST localhost:8000/ask_question lang="pt" question="Quanto tempo sobrevive o vírus nas superfícies?"

echo "DONE!"
