echo "Starting PT QA testing..."

echo "Q1:"
http POST localhost:8000/ask_question lang="pt" question="Como se transmite a COVID-19?"
echo "Q2:"
http POST localhost:8000/ask_question lang="pt" question="Quais são os sintomas da COVID-19?"
echo "Q3:"
http POST localhost:8000/ask_question lang="pt" question="Como posso saber se tenho COVID-19 ou uma constipação?"
echo "Q4:"
http POST localhost:8000/ask_question lang="pt" question="O vírus que transmite a COVID-19 pode ser transmitido pelo ar?"
echo "Q5:"
http POST localhost:8000/ask_question lang="pt" question="O que posso fazer para me proteger e evitar a disseminação da doença?"
echo "Q6:"
http POST localhost:8000/ask_question lang="pt" question="Devo usar máscara enquanto faço exercício?"
echo "Q7:"
http POST localhost:8000/ask_question lang="pt" question="Os sintomas da COVID-19 são diferentes nos adultos e nas crianças?"
echo "Q8:"
http POST localhost:8000/ask_question lang="pt" question="Os antibióticos são eficazes na prevenção ou tratamento da COVID-19?"
echo "Q9:"
http POST localhost:8000/ask_question lang="pt" question="Os humanos podem ser infetados com a COVID-19 através de animais?"
echo "Q10:"
http POST localhost:8000/ask_question lang="pt" question="Quanto tempo sobrevive o vírus nas superfícies?"

echo "DONE!"
